version: "3.9"
services:
  selenium:
    image: "selenium/standalone-chrome:latest"
    ports:
      - "4444:4444"
  frontend:
    build: ../frontend
    ports:
      - "8888:80"
  backend:
    build: ../backend
    env_file:
      - backend.env
    links:
      - mysql
  mysql:
    build: ../mysql
    ports:
      - "3306:3306"
    env_file:
      - mysql.env
